name: qabstracts data checks
run-name: ${{ github.actor }}
on: [push]
jobs:
  Check-Codings:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: check-codings
        run: |
          # ls ${{ github.workspace }}
          git log --oneline -10
          # sudo apt install poppler-utils
          pip -q install -r requirements.txt
          # PYTHONPATH=script pytest -v
          set +e
          echo "*****************************"
          echo "****** prestudy2     ********"
          echo "*****************************"
          python script/qabstracts.py check-codings prestudy2 && python script/qabstracts.py compare-codings prestudy2
          prestudy_status = $?
          echo " "
          echo " "
          echo " "
          echo "*****************************"
          echo "****** full study    ********"
          echo "*****************************"
          python script/qabstracts.py check-codings abstracts && python script/qabstracts.py compare-codings abstracts 
          fullstudy_status = $?
          echo "?????????????????????????"
          echo "'prestudy2/' had $prestudy_status errors" 
          echo "'abstracts/' had $fullstudy_status errors" 
          exit $((prestudy_status+fullstudy_status))
