name: qabstracts CI
run-name: ${{ github.actor }}
on: 
  push:
    paths:
      - '.github/workflows/fullstudy.yml'
      - 'Makefile'
      - 'abstracts/**'
      - 'script/**'
      - 'tex/**'
jobs:
  check-and-compare-codings:  # yml errors? try  https://rhysd.github.io/actionlint/
    runs-on: ubuntu-22.04
    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: check and compare codings
        run: |
          git log --oneline -10
          pip -q install -r requirements.txt
          set -e
          echo "*****************************"
          echo "****** full study    ********"
          echo "*****************************"
          python script/qabstracts.py check-codings abstracts && python script/qabstracts.py compare-codings abstracts
  process-fullstudy:
    runs-on: ubuntu-22.04
    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        run: |
          pip -q install -r requirements.txt
          make export
          make plotall
          # We check out only the last revision -> no Git history -> no timeline data -> use pre-rendered timeline from version control
          git restore img/qabstracts_timeline_commits.pdf
          ls -l img
          sudo apt-get update
          sudo apt install texlive-xetex latexmk
          make pdf
      - name: upload PDF
        uses: actions/upload-artifact@v4
        with: 
          name: 'qabstracts-tse.pdf'
          path: 'tex/qabstracts-tse.pdf'
