name: qabstracts CI
run-name: ${{ github.actor }}
on: 
  push:
    paths:
      - '.github/workflows/fullstudy.yml'
      - 'Makefile'
      - 'abstracts/**'
      - 'script/**'
      - 'tex/**'

jobs:
  check-and-compare-codings:  # yml errors? try  https://rhysd.github.io/actionlint/
    runs-on: ubuntu-22.04
    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: check and compare codings
        run: |
          git log --oneline -10
          pip -q install -r requirements.txt
          set -e
          echo "*****************************"
          echo "****** full study    ********"
          echo "*****************************"
          python script/qabstracts.py check-codings abstracts && python script/qabstracts.py compare-codings abstracts

  process-fullstudy:
    runs-on: ubuntu-22.04
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: "${{ github.repository }}-knitr-py:latest"
    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: login to GitHub registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up Docker
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          echo "RUN_CMD=docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: analyze data
        run: |
          # We need to add /workspace as a safe directory because we are running a git command under the hood
          ${{ env.RUN_CMD }} bash -c "git config --global --add safe.directory /workspace && make export"
          ${{ env.RUN_CMD }} make plotall
          # We check out only the last revision -> no Git history -> no timeline data -> use pre-rendered timeline from version control
          git restore img/qabstracts_timeline_commits.pdf
          ls -l img

      - name: knit report
        run: |
          ${{ env.RUN_CMD }} make pdf KNIT_ARGS=debug
          mv tex/qabstracts-tse.pdf tex/qabstracts-tse-debug.pdf
          ${{ env.RUN_CMD }} make pdf

      - name: upload PDF
        uses: actions/upload-artifact@v4
        with: 
          name: 'qabstracts-tse'
          path: |
            'tex/qabstracts-tse-debug.pdf'
            'tex/qabstracts-tse.pdf'
