name: qabstracts CI
run-name: ${{ github.actor }}
on: 
  push:
    paths:
      - '.github/workflows/fullstudy.yml'
      - 'abstracts/**'
      - 'script/**'
      - 'tex/**'
jobs:
  process-fullstudy:  # yml errors? try  https://rhysd.github.io/actionlint/
    runs-on: ubuntu-22.04
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: build
        run: |
          git log --oneline -10
          pip -q install -r requirements.txt
          set -e
          echo "*****************************"
          echo "****** full study    ********"
          echo "*****************************"
          python script/qabstracts.py check-codings abstracts && python script/qabstracts.py compare-codings abstracts 
          make export
          make plot
          apt install texlive-xetex
          make pdf
      - name: upload PDF
        uses: actions/upload-artifact@v3
        with: 
          name: 'qabstracts-tse.pdf'
          path: 'tex/qabstracts-tse.pdf'